[profile.default]
src = 'scripts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'forge-cache'
allow_paths = ["../node_modules"]
solc = '0.8.17'
optimizer = true
optimizer_runs = 999_999
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.ci]
verbosity = 4
